### ISSUE TITLE
[16.4.2] Implementing AutoRec (AutoRec와 MLP 구현이 거의 같아보이는데, 다른 차별점이 있는지?)

### ISSUE THREAD

**Issue by staycozyboy** [woowacampers/d2l-pytorch#10]
![image](https://user-images.githubusercontent.com/37537248/108788850-482ad480-75bc-11eb-84ff-a555fa291705.png)

```python
class AutoRec(nn.Block):
    def __init__(self, num_hidden, num_users, dropout=0.05):
        super(AutoRec, self).__init__()
        self.encoder = nn.Dense(num_hidden, activation='sigmoid',
                                use_bias=True)
        self.decoder = nn.Dense(num_users, use_bias=True)
        self.dropout = nn.Dropout(dropout)

    def forward(self, input):
        hidden = self.dropout(self.encoder(input))
        pred = self.decoder(hidden)
        if autograd.is_training():  # Mask the gradient during training
            return pred * np.sign(input)
        else:
            return pred
```

이게 표현이 달라서 그렇지 구현된 코드를 보면 2층 MLP와의 차이점을 잘 모르겠네요. encoder랑 decoder가 단순한 dense layer로 구현된 것도, 그렇고 그냥 affine transformation 하고 activation하는 걸 굳이 encoder와 decoder의 개념으로 설명한 것도 잘 모르겠습니다. 이건 제가 AutoEncoder의 개념을 잘 몰라서 그런 것 같기도 한데, 일단 올려봅니당.

**Comment by jiwon-ryu** [comment]
넵 MLP와 구조적으로 같은게 맞고, 다만 오토인코더에서는 학습하려는 target이 자기자신인 점이 차이점이라고 알고 있습니당~

**Comment by staycozyboy** [comment]
### 스터디
지원님: 넵 MLP와 구조적으로 같은게 맞고, 다만 오토인코더에서는 학습하려는 target이 자기자신인 점이 차이점이라고 알고 있습니당~

MNIST를 더 작은 차원의 hidden layer로 만들고, decoder(저차원에서 고차원으로 복원을 시키는 역할), Encoder(노이즈를 제거하는 역할), 출력이 깨끗한 이미지가 되도록.

다혜님: [https://tech.kakao.com/2020/04/29/kakaoarena-3rd-part1/](https://tech.kakao.com/2020/04/29/kakaoarena-3rd-part1/)
