### ISSUE TITLE
[16.5.1] Bayesian Personalized Ranking Loss에서 maximum posterior estimator 계산

### ISSUE THREAD

**Issue by jiwon-ryu** [woowacampers/d2l-pytorch#12]
수식 16.5.2의 첫번째줄에서 두번째줄로 어떻게 넘어가는 것인지 궁금합니다

> ![image](https://user-images.githubusercontent.com/69613571/108810815-51816480-75ef-11eb-9e22-642551138dad.png)

**Comment by jiwon-ryu** [comment]
한결님이 추천해주신 블로그:
https://leehyejin91.github.io/post-bpr/

**Comment by staycozyboy** [comment]
### 스터디
지원님: 수식 16.5.2의 첫번째줄에서 두번째줄로 어떻게 넘어가는 것인지 궁금합니다.

  * 인규: It assumes that the user prefers the positive item over all other non-observed items.

다혜님: $\sigma(\hat{y_{ui}} - \hat{y_{uj}})$ 에 대한 이해가 안됨.
  * 지원님: 세타라는 모델을 만들었을 때, 사용자가 실제로 선호하는 랭킹을 나타내는 파라미터를 가지는 모델일 확률? 을 최대화 시켜줘야하는 것. 따라서 사용자가 선호하는 아이템에 대한 점수와 사용자가 관찰하지 않은 아이템에 대한 점수를 최대화 시켜주는 것을 목적으로 한다. 즉, 그 차이를 최대화 시켜야 p값이 1에 가까워 지는 것.

재완님: 더 정확한 이해를 위해서는 논문을 제대로 봐야할 것 같다.

**Comment by jiwon-ryu** [comment]
최대사후확률 (maximum posterior estimator)의 정의는 아래와 같다

> ![image](https://user-images.githubusercontent.com/69613571/111596661-bc017b00-8810-11eb-8efc-7b8749557be2.png)
