### ISSUE TITLE
[16.6.1] NeuMF 모델의 input 벡터 차이

### ISSUE THREAD

**Issue by dhh0** [woowacampers/d2l-pytorch#14]
![image](https://user-images.githubusercontent.com/76548813/108958512-7096f980-76b6-11eb-84cc-06ae94b711de.png)

사진에서 input으로 들어가는 p_u, u_u 가 user 정보, q_i, v_i 가 item 정보인데 이 벡터들의 차이점이 있는지 궁금합니다!

**Comment by staycozyboy** [comment]
### 스터디
인규: p, q → user & item latent vector, u, v → user & item embeddings, 비슷한 개념이라도 표현을 달리한데는 분명 근본적인 개념의 차이가 있다고 생각함. 제가 AutoRec과 MLP 차이점 질문한거랑 비슷한 결. 따라서, 둘 다 그냥 수학적으로 봤을 때, 다른 차원으로 transformation한다라는 것은 같지만, 목적이 다르다고 생각한다. latent vector의 경우 matrix factorization을 위한 것이고, embedding의 경우 어떤 추상적인 개념을 수학적인 벡터로 represent하기 위해 transformation해주는 것.

지원님: To enrich model flexibility, the MLP subnetwork does not share user and item embeddings with GMF. → 다른 차원으로 transformation 하는 것 같습니다.
