### ISSUE TITLE
[10.6.2] Comparing CNNs, RNNs, and Self-Attention

### ISSUE THREAD

**Issue by staycozyboy** [woowacampers/d2l-pytorch#18]
### CNN
> For now, we only need to know that since the sequence length is  n , the numbers of input and output channels are both  d , the computational complexity of the convolutional layer is  O(knd2) . As Fig. 10.6.1 shows, CNNs are hierarchical so there are  O(1)  sequential operations and the maximum path length is  O(n/k) . For example,  x1  and  x5  are within the receptive field of a two-layer CNN with kernel size 3 in Fig. 10.6.1.

### RNN
> When updating the hidden state of RNNs, multiplication of the  d×d  weight matrix and the  d -dimensional hidden state has a computational complexity of  O(d2) . Since the sequence length is  n , the computational complexity of the recurrent layer is  O(nd2) . According to Fig. 10.6.1, there are  O(n)  sequential operations that cannot be parallelized and the maximum path length is also  O(n) .

### Self-Attention
> n self-attention, the queries, keys, and values are all  n×d  matrices. Consider the scaled dot-product attention in (10.3.5), where a  n×d  matrix is multiplied by a  d×n  matrix, then the output  n×n  matrix is multiplied by a  n×d  matrix. As a result, the self-attention has a  O(n2d)  computational complexity. As we can see in Fig. 10.6.1, each token is directly connected to any other token via self-attention. Therefore, computation can be parallel with  O(1)  sequential operations and the maximum path length is also  O(1) .

CNN, RNN, Self-Attention을 computational complexity, sequential operations, maximum path length 측면에서 비교하고 있는데요. 그냥 전체적으로 위의 문장들이 이해가 안되네요. Attention Is All You Need에서도 똑같은 비교를 하고 있는데, 논문과 설명이 거의 똑같습니다. 주재걸 교수님 강의에서도 다뤄주셔서, 그땐 좀 이해가 되었던 것 같은데, 다시 보니 이해를 못하고 있었네요. 레퍼런스보면서 다시 한번 공부하고 정리하려고 이슈 올립니다. 혹시 저처럼 이해가 안되시거나, 설명해주시고 싶은 분은 코멘트 달아주시면 감사하겠습니다 :)

**Comment by staycozyboy** [comment]
![image](https://user-images.githubusercontent.com/37537248/110079000-daf11d80-7dcb-11eb-9c17-f289173de3c6.png)

1. RNN
    * Complexity per Layer: 가장 연산량이 많은 연산은 W_hh와 h_t의 곱이다. 이는 d by d인 weight matrix와 d 차원의 hidden state vector의 곱이므로, O(d^2)이다. 이 연산을 sequence length만큼 반복하니까 O(nd^2).
    * Sequential Operations: h_t를 계산하기 위해서는 h_t-1의 계산이 선행되어야한다. 따라서, 병렬처리 될 수 없는 maximum path length는 전체 time-step. O(n)이다.
    * Maximum Path Length: 이는 long-term dependency와 관련된 연산? 조금 더 쉽게 이해하자면 worst indexing cost 정도의 개념으로 이해된다. (이 cost가 작을 수록 long-term dependecy를 잘 반영한다고 생각할 수 있다) 가장 멀리 떨어져있는 time-step을 고려하기 위해서는 n번의 연산을 거쳐야하기 때문에 O(n).
2. Self-Attention
    * Complexity per Layer: 가장 연산량이 많은 연산은 Q와 K^T의 곱. 이는 n by d인 Q와 d by n인 K^T의 곱이므로, O(n^2d)이다.
    * Sequential Operation: 각각의 query-key matrix multiplication 쌍은 서로에게 종속적이지 않고 독립적으로 계산될 수 있기 때문에, GPU 리소스가 지원된다면 O(1)에 모든 연산을 병렬적으로 수행할 수 있다.
    * Maximum Sequence Length: self-attention mechanism을 생각해보자. 각 query는 모든 input의 attention을 바로 접근할 수 있다. 따라서 O(1).
3. CNN
    * 얘는 조금 더 봐야할 것 같다 ㅠㅠ

**Comment by jiwon-ryu** [comment]
CNN - 본문과 Table에서 maximum path length가 다름

'Attention is All You Need'의 설명:
> A single convolutional layer with kernel width k < n does not connect all pairs of input and output
positions. Doing so requires a stack of O(n/k) convolutional layers in the case of contiguous kernels,
or O(logk(n)) in the case of dilated convolutions

**Comment by staycozyboy** [comment]
### CNN
1. Complexity per Layer: activation map size를 n으로 가정 혹은 근사한 것 같다. kernel size가 k이므로 O(knd^2).
2. CNN은 hierarchical한 구조를 가지기 때문에, 각각의 연산은 독립적으로 수행될 수 있다. 즉, 병렬 처리될 수 있다. 따라서, sequential operation은 O(1)이다.
3. Maximum path length: regular conv의 경우, receptive field의 size가 linear하게 증가하기 때문에 O(n/k) 만큼의 layer가 필요하다. dilated conv의 경우, dilated conv의 개념을 조금 더 명확하게 공부하고 다시 살펴볼 필요가 있다.
