### ISSUE TITLE
[8.1.1] Autoregressive Models 개념에 대한 명확한 이해

### ISSUE THREAD

**Issue by staycozyboy** [woowacampers/d2l-pytorch#2]
> Such models will be called autoregressive models, as they quite literally perform regression on themselves.
> [8.1.1.1 2번째 문단 마지막 문장](https://d2l.ai/chapter_recurrent-neural-networks/sequence.html#autoregressive-models)

여기서, *literally perform regression on themselves*가 RNN의 구조를 생각했을 때 대략적으로는 어떤 느낌을 말하는지 알겠는데, 명쾌하게 개념이 딱 잡히지는 않는 것 같아서 일단 적어봅니당 ㅎㅎ

**Comment by jiwon-ryu** [comment]
자기 자신의 내부 구조를 예측해나간다는 점에서 auto + regression -> autoregressive model이라고 하는 것 같습니다~
