### ISSUE TITLE
[13.4.2] IoU 구현

### ISSUE THREAD

**Issue by jiwon-ryu** [woowacampers/d2l-pytorch#21]
![image](https://user-images.githubusercontent.com/69613571/110285292-5fd77380-8026-11eb-83f2-9297f1c1b5ae.png)

교집합 구하는 부분을 아직 이해하지 못해서 올려 두었습니다.

torch.clamp 함수에 대한 내용은 다음과 같았어요
https://pytorch.org/docs/stable/generated/torch.clamp.html

**Comment by staycozyboy** [comment]
### 스터디
- 지원님: IoU 구현
    - 교집합 구하는 부분의 코드 lt, rb?
    - 인규: lt → left top, rb → right bottom. 각각 좌표에 대한 tensor인 것 같아요.
- 지원님: (s1, r1) ... (s1, rm), (s2, r1), (s3, r1), ... , (sn, r1)
    - 표기가 이상함 왜 rm까지 안가지는지?
    - 인규: 축약한 게 맞는 것 같습니다.

**Comment by jiwon-ryu** [comment]
`lt`: 두개의 left top 좌표 중 큰 값 (x_1, y_1)
`rb`: 두개의 right bottom 좌표 중 작은 값 (x_2, y_2)

`wh`: intersection의 width와 height
`(rb-lt).clamp(min=0)`: 0보다 작으면 0을 return
-> 두 사각형이 겹치지 않는 경우 `x_1 > x_2`, `y_1 > y_2`가 되어 `rb-lt`가 음수가 됨. 그때는 그냥 Intersection=0 만들어줌
