### ISSUE TITLE
[8.4.4] Perplexity에 대한 설명

### ISSUE THREAD

**Issue by jiwon-ryu** [woowacampers/d2l-pytorch#3]
![image](https://user-images.githubusercontent.com/69613571/108162799-2ac7b780-7131-11eb-9316-e1549cb47a75.png)

위의 Eq 8.4.8에 대해 다음 설명은 무엇을 의미하는 걸까요?

![image](https://user-images.githubusercontent.com/69613571/108162781-1f748c00-7131-11eb-91a2-9bcf2695f35a.png)

**Comment by jiwon-ryu** [comment]
* eq 8.4.8의 exponential로 표현된 perplexity가 왜 harmonic mean을 의미하는지는 모르겠지만,
설명에 나와 있는 harmonic mean에만 초점을 맞추어 생각해보면 3 가지 경우 (best, worst, baseline)에 대해 harmonic mean이 다음과 같음을 알 수 있습니다.

**1. best** -> n개의 P 값이 1
`harmonic mean` = n / (1 + ... + 1) = 1
**2. worst** -> n개의 P값이 0
`harmonic mean` = n / (0 + ... + 0) = inf
**3. baseline** -> n개의 P값이 1/n (uniform distribution)
`harmonic mean` = n / (1/n + ... + 1/n) = n

**Comment by 1gyeol-KIM** [comment]
- 밑의 지문의 의미는 아직도 이해가 잘 안되지만, 엔트로피와 perplexity의 관계에 대해 설명한 글이 있어서 레퍼런스 남길게요.
- 링크 맨 밑 문단 "엔트로피와 perplexity의 관계" (eq 8.4.7 -> eq 8.4.8 )
[Text Generation Evaluation 03 - Perplexity](https://ai-information.blogspot.com/2019/03/text-generation-evaluation-03-perplexity.html)

**Comment by jiwon-ryu** [comment]
issue 요약: perplexity와 harmonic mean은 서로 어떤 연관성이 있는가?
결론: harmonic mean이 아니라 geometric mean인 것 같다.

### 1. 검색 결과 harmonic mean과의 연관성을 설명한 reference를 찾기 어려웠고, 여러 링크들에서 '문장의 확률의 기하평균'으로 설명하는 것을 찾았다.
* https://ai-information.blogspot.com/2019/03/text-generation-evaluation-03-perplexity.html
* https://stats.stackexchange.com/questions/10302/what-is-perplexity

### 2. Cross Entropy와 Perplexity의 관계
* 문장 내 n개 토큰들의 평균 cross entropy (a.k.a. entropy rate)는 다음과 같다 (d2l의 식)
![image](https://user-images.githubusercontent.com/69613571/109792333-bde70e00-7c56-11eb-8860-42c6efcb6d1c.png)
* 이를 정리하면 다음과 같다 (단순 로그 계산)
![image](https://user-images.githubusercontent.com/69613571/109792793-3bab1980-7c57-11eb-85e0-82e38477194a.png)

*  perplexity는 다음처럼 기하평균을 이용하여 정의된다 (한결님 ref의 식)
![image](https://user-images.githubusercontent.com/69613571/109792441-de16cd00-7c56-11eb-9ed0-eeb69853b84f.png)
* 따라서 다음이 성립함을 알 수 있다
`Perplexity = exp(Cross Entropy)`
